SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS api_schedules (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  schedule_type VARCHAR(32) NOT NULL UNIQUE,
  interval_minutes INT NOT NULL DEFAULT 60,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  last_run_at DATETIME NULL,
  lock_until DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET @api_logs_exists := (
  SELECT COUNT(*) FROM information_schema.TABLES
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'api_logs'
);

SET @sql := IF(
  @api_logs_exists = 0,
  'CREATE TABLE api_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, api_name VARCHAR(64) NOT NULL, request_url TEXT NOT NULL, request_hash CHAR(64) NOT NULL, response_status INT NULL, response_body MEDIUMTEXT NULL, cache_hit TINYINT(1) NOT NULL DEFAULT 0, endpoint VARCHAR(64) NULL, request_params LONGTEXT NULL, status_code INT NULL, is_success TINYINT(1) NOT NULL DEFAULT 0, message VARCHAR(255) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_api_logs_created (created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

ALTER TABLE api_logs ADD COLUMN IF NOT EXISTS endpoint VARCHAR(64) NULL AFTER api_name;
ALTER TABLE api_logs ADD COLUMN IF NOT EXISTS request_params LONGTEXT NULL AFTER endpoint;
ALTER TABLE api_logs ADD COLUMN IF NOT EXISTS status_code INT NULL AFTER response_status;
ALTER TABLE api_logs ADD COLUMN IF NOT EXISTS is_success TINYINT(1) NOT NULL DEFAULT 0 AFTER status_code;
ALTER TABLE api_logs ADD COLUMN IF NOT EXISTS message VARCHAR(255) NULL AFTER is_success;
