SET NAMES utf8mb4;

ALTER TABLE partner_sites
  ADD COLUMN IF NOT EXISTS show_link TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE partner_rss
  ADD COLUMN IF NOT EXISTS show_rss TINYINT(1) NOT NULL DEFAULT 1;
