SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS admins (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_password_resets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  admin_user_id INT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_admin_password_resets_lookup (token_hash, used_at, expires_at),
  CONSTRAINT fk_admin_password_resets_admin
    FOREIGN KEY (admin_user_id) REFERENCES admins(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  setting_key VARCHAR(191) PRIMARY KEY,
  setting_value LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dmm_sites (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  site_code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dmm_services (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  site_code VARCHAR(50) NOT NULL,
  service_code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_services_site FOREIGN KEY (site_code) REFERENCES dmm_sites(site_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dmm_floors (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  service_code VARCHAR(50) NOT NULL,
  floor_code VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_service_floor (service_code, floor_code),
  CONSTRAINT fk_floor_service FOREIGN KEY (service_code) REFERENCES dmm_services(service_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS actresses (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dmm_id VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  ruby VARCHAR(255) NULL,
  birthday VARCHAR(20) NULL,
  prefectures VARCHAR(255) NULL,
  image_url TEXT NULL,
  image_small TEXT NULL,
  image_large TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS genres LIKE actresses;
ALTER TABLE genres MODIFY dmm_id VARCHAR(64) NOT NULL UNIQUE;
CREATE TABLE IF NOT EXISTS makers LIKE actresses;
ALTER TABLE makers MODIFY dmm_id VARCHAR(64) NOT NULL UNIQUE;
CREATE TABLE IF NOT EXISTS series_master LIKE actresses;
ALTER TABLE series_master MODIFY dmm_id VARCHAR(64) NOT NULL UNIQUE;
CREATE TABLE IF NOT EXISTS authors LIKE actresses;
ALTER TABLE authors MODIFY dmm_id VARCHAR(64) NOT NULL UNIQUE;

CREATE TABLE IF NOT EXISTS items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  content_id VARCHAR(128) NOT NULL UNIQUE,
  product_id VARCHAR(128) NULL,
  item_source VARCHAR(32) NOT NULL DEFAULT 'unknown',
  title TEXT NOT NULL,
  service_code VARCHAR(64) NULL,
  service_name VARCHAR(255) NULL,
  floor_code VARCHAR(64) NULL,
  floor_name VARCHAR(255) NULL,
  category_name VARCHAR(255) NULL,
  volume VARCHAR(255) NULL,
  review_count INT NULL,
  review_average DECIMAL(3,2) NULL,
  view_count INT NOT NULL DEFAULT 0,
  url TEXT NULL,
  affiliate_url TEXT NULL,
  image_list TEXT NULL,
  image_small TEXT NULL,
  image_large TEXT NULL,
  sample_movie_url_476 TEXT NULL,
  sample_movie_url_560 TEXT NULL,
  sample_movie_url_644 TEXT NULL,
  sample_movie_url_720 TEXT NULL,
  sample_movie_pc_flag TINYINT(1) NOT NULL DEFAULT 0,
  sample_movie_sp_flag TINYINT(1) NOT NULL DEFAULT 0,
  price_min_text VARCHAR(255) NULL,
  list_price_text VARCHAR(255) NULL,
  release_date DATE NULL,
  raw_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_items_view_count (view_count, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_actresses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  actress_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_item_actresses_dmm_item (dmm_id, item_id),
  CONSTRAINT fk_item_actress_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_genres (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  genre_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_item_genres_dmm_item (dmm_id, item_id),
  CONSTRAINT fk_item_genre_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_campaigns (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  campaign_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_item_campaign_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_labels (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  label_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_item_label_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_directors (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  director_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_item_director_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS item_makers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  maker_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_item_maker (item_id, dmm_id),
  INDEX idx_item_makers_dmm_item (dmm_id, item_id),
  CONSTRAINT fk_item_maker_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_series (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  series_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_item_series (item_id, dmm_id),
  INDEX idx_item_series_dmm_item (dmm_id, item_id),
  CONSTRAINT fk_item_series_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_authors (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  author_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_item_author (item_id, dmm_id),
  CONSTRAINT fk_item_author_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_actors (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  dmm_id VARCHAR(64) NULL,
  actor_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_item_actor (item_id, dmm_id),
  CONSTRAINT fk_item_actor_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS page_views (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  viewed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip_hash VARCHAR(64) NULL,
  user_agent VARCHAR(255) NULL,
  INDEX idx_page_views_item_date (item_id, viewed_at),
  INDEX idx_page_views_item_ip_date (item_id, ip_hash, viewed_at),
  CONSTRAINT fk_page_views_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS item_tags (
  item_id INT UNSIGNED NOT NULL,
  tag_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (item_id, tag_id),
  INDEX idx_item_tags_tag (tag_id),
  CONSTRAINT fk_item_tags_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
  CONSTRAINT fk_item_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS api_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  api_name VARCHAR(64) NOT NULL,
  request_url TEXT NOT NULL,
  request_hash CHAR(64) NOT NULL,
  response_status INT NULL,
  response_body MEDIUMTEXT NULL,
  cache_hit TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_api_logs_created (created_at),
  INDEX idx_api_logs_name (api_name),
  INDEX idx_api_logs_hash (request_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sync_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sync_type VARCHAR(50) NOT NULL,
  is_success TINYINT(1) NOT NULL,
  synced_count INT NOT NULL DEFAULT 0,
  message TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS sync_job_state (
  job_key VARCHAR(64) PRIMARY KEY,
  next_offset INT NOT NULL DEFAULT 1,
  next_initial VARCHAR(10) NULL,
  last_run_at DATETIME NULL,
  last_success TINYINT(1) NOT NULL DEFAULT 0,
  last_message TEXT NULL,
  lock_until DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS api_schedules (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  schedule_type VARCHAR(32) NOT NULL UNIQUE,
  interval_minutes INT NOT NULL DEFAULT 60,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  last_run_at DATETIME NULL,
  lock_until DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS site_article_feed_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  feed_key VARCHAR(32) NOT NULL,
  item_id INT UNSIGNED NOT NULL,
  content_id VARCHAR(128) NULL,
  published_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_site_article_feed_item (feed_key, item_id),
  INDEX idx_site_article_feed_published (feed_key, published_at),
  INDEX idx_site_article_feed_item_date (feed_key, item_id, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reciprocal_sites (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  note TEXT NULL,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reciprocal_links (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  site_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  image_url TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_reciprocal_links_site (site_id),
  CONSTRAINT fk_reciprocal_links_site FOREIGN KEY (site_id) REFERENCES reciprocal_sites(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reciprocal_rss (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  site_id BIGINT UNSIGNED NOT NULL,
  feed_url TEXT NOT NULL,
  last_fetched_at DATETIME NULL,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_reciprocal_rss_site (site_id),
  CONSTRAINT fk_reciprocal_rss_site FOREIGN KEY (site_id) REFERENCES reciprocal_sites(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reciprocal_rss_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  rss_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  link TEXT NOT NULL,
  published_at DATETIME NULL,
  image_url TEXT NULL,
  hash CHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_reciprocal_rss_item_hash (rss_id, hash),
  INDEX idx_reciprocal_rss_published (published_at),
  CONSTRAINT fk_reciprocal_rss_items_rss FOREIGN KEY (rss_id) REFERENCES reciprocal_rss(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS site_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  event_type ENUM('in','out','pv') NOT NULL,
  path VARCHAR(255) NULL,
  referrer VARCHAR(500) NULL,
  ua_hash CHAR(64) NULL,
  ip_hash CHAR(64) NULL,
  session_id_hash CHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_site_events_type_date (event_type, created_at),
  INDEX idx_site_events_session_date (session_id_hash, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS daily_kpi (
  kpi_date DATE PRIMARY KEY,
  pv INT NOT NULL DEFAULT 0,
  uu INT NOT NULL DEFAULT 0,
  in_count INT NOT NULL DEFAULT 0,
  out_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS out_clicks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  to_url TEXT NOT NULL,
  label VARCHAR(255) NULL,
  session_id_hash CHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_out_clicks_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
